// Generated by CoffeeScript 1.4.0
(function() {
  var MainRouter, ProblemView, QuestionSet, Session;

  window.app || (window.app = {});

  MainRouter = Backbone.Router.extend({
    routes: {
      '': 'root',
      'config': 'config',
      'reset': 'reset',
      'finished': 'finished',
      'practice': 'math',
      'practice/:operation': 'math',
      'practice/:operation/:group': 'math'
    },
    root: function() {},
    math: function(operation, group) {
      if (operation == null) {
        operation = 'addition';
      }
      if (group == null) {
        group = '0';
      }
      app.session || (app.session = new app.Session());
      app.session.push(new app.QuestionSet({
        operation: operation,
        group: group
      }));
      return (new app.ProblemView()).initilize();
    },
    reset: function() {},
    config: function() {},
    finished: function() {
      return alert('finished');
    }
  });

  app.router = new MainRouter();

  window.app || (window.app = {});

  $(function() {
    return Backbone.history.start();
  });

  window.app || (window.app = {});

  Session = Backbone.Collection.extend({
    localStorage: new Backbone.LocalStorage('Session'),
    allOperations: ['addition', 'subtraction'],
    setsPerOperation: 10,
    getLastQuestionSet: function() {
      return this.models.slice(-1)[0];
    },
    finishedWithOperation: function() {
      var lastQuestionSet;
      lastQuestionSet = this.getLastQuestionSet();
      if (Number(this.setsPerOperation) === Number(lastQuestionSet.get('group'))) {
        return lastQuestionSet.finishedWithSet();
      }
      return false;
    },
    nextRound: function() {
      var lastQuestionSet, nextOperation, operation;
      lastQuestionSet = this.getLastQuestionSet();
      operation = lastQuestionSet.get('operation');
      if (operation === this.allOperations.slice(-1)[0]) {
        return app.router.navigate('finished', {
          trigger: true
        });
      } else {
        nextOperation = this.allOperations[1 + this.allOperations.indexOf(operation)];
        return app.router.navigate("practice/" + nextOperation + "/0", {
          trigger: true
        });
      }
    }
  });

  app.Session = Session;

  window.app || (window.app = {});

  ProblemView = Backbone.View.extend({
    el: '#problemContainer',
    initilize: function() {
      var _ref;
      if ((_ref = app.lastProblemView) != null) {
        _ref.undelegateEvents();
      }
      app.lastProblemView = this;
      return this.displayNextQuestion();
    },
    events: {
      'submit form': 'grade'
    },
    displayNextQuestion: function() {
      return this.render(app.session.getLastQuestionSet().getNewQuestion());
    },
    render: function(data) {
      var newProblem;
      if (data == null) {
        data = {};
      }
      newProblem = $("#problem-template-" + (_.random(0, 2))).html();
      $('#problemContainer').html(_.template(newProblem, data));
      return this;
    },
    grade: function(event) {
      var correct, correctAnswer, lastQuestionSet, nextQuestionForm, _ref,
        _this = this;
      event.preventDefault();
      lastQuestionSet = app.session.getLastQuestionSet();
      _ref = lastQuestionSet.answerQuestion(this.$el.find('input[name=answer]').val()), correct = _ref.correct, correctAnswer = _ref.correctAnswer;
      nextQuestionForm = null;
      if (correct) {
        nextQuestionForm = $(_.template($('#correct').html(), {}));
      } else {
        nextQuestionForm = $(_.template($('#incorrect').html(), {
          correctAnswer: correctAnswer
        }));
      }
      $('#problemContainer').html(nextQuestionForm);
      $('.nextQuestion').on('click', function() {
        return _this.displayNextQuestion();
      });
      if (app.session.finishedWithOperation()) {
        return app.session.nextRound();
      } else if (lastQuestionSet.finishedWithSet()) {
        return app.router.navigate("practice/" + (lastQuestionSet.get('operation')) + "/" + (1 + Number(lastQuestionSet.get('group'))), {
          trigger: true
        });
      }
    }
  });

  window.app.ProblemView = ProblemView;

  window.app || (window.app = {});

  QuestionSet = Backbone.Model.extend({
    defaults: {
      operation: 'addition',
      group: '0',
      currentOperand: null,
      asked: {}
    },
    questionsPerSet: 11,
    initialize: function() {
      return this.set('asked', {});
    },
    getNewQuestion: function() {
      var operand;
      while (true) {
        operand = _.random(0, this.questionsPerSet - 1);
        if (!_.contains(_.keys(this.get('asked')), "" + operand)) {
          break;
        }
      }
      this.set('currentOperand', operand);
      if (this.get('operation') === 'subtraction') {
        return {
          operand0: Math.max(this.get('group'), operand),
          operand1: Math.min(this.get('group'), operand),
          operator: '-'
        };
      } else {
        if (_.random(0, 1) % 2) {
          return {
            operand0: this.get('group'),
            operand1: operand,
            operator: '+'
          };
        } else {
          return {
            operand0: operand,
            operand1: this.get('group'),
            operator: '+'
          };
        }
      }
    },
    finishedWithSet: function() {
      return _.keys(this.get('asked')).length === this.questionsPerSet;
    },
    answerQuestion: function(submittedAnswer) {
      var correct, correctAnswer;
      correctAnswer = null;
      if (this.get('operation') === 'addition') {
        correctAnswer = Number(this.get('currentOperand')) + Number(this.get('group'));
      }
      if (this.get('operation') === 'subtraction') {
        correctAnswer = Math.abs(Number(this.get('currentOperand')) - Number(this.get('group')));
      }
      correct = (submittedAnswer != null ? submittedAnswer.trim().length : void 0) ? correctAnswer === Number(submittedAnswer) : false;
      this.get('asked')["" + (this.get('currentOperand'))] = {
        correct: correct,
        submittedAnswer: submittedAnswer
      };
      return {
        correct: correct,
        correctAnswer: correctAnswer
      };
    }
  });

  app.QuestionSet = QuestionSet;

}).call(this);
